### ISSUE TITLE
Showing the current category isSelected

### ISSUE THREAD

**Issue by soggybag** [StephanieCherubin/React-Shoppe#11]
https://github.com/StephanieCherubin/React-Shoppe/blob/937194c43b377ceef829c73e41ab76eeb93c9fd0/src/Sidebar.js#L19

The problem with showing the current category is here. Look really close at this line and ask yourself what is happening? 

```
isSelected={currentCategory === 'cats`}
```

With the quotation marks your matching the string. Don't you really want to match the value stored in the variable? 

Fixing this here will still not show the button as selected in the browser since you haven't a style for this yet. You should be able to see the 'selected' class on the button that was clicked when if you inspect it. Try this out.

**Comment by StephanieCherubin** [comment]
Fixed
